[package]
name = "process_watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
getopts = "0.2.21"
sysinfo = "0.26.2"
tray-item = "0.7.1"
windows = "0.39.0"

[build-dependencies]
windres = "0.2.2"
